name: t_rent
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  intl: ^0.20.2
  get_it: ^8.2.0
  equatable: ^2.0.7
  auto_route: ^10.1.2
  flutter_bloc: ^9.1.1
  logger: ^2.6.2
  email_validator: ^3.0.0
  pinput: ^5.0.2
  svg_flutter: ^0.0.1
  latlong2: ^0.9.1
  mapbox_maps_flutter: ^2.11.0
  geolocator: ^14.0.2
  flutter_dotenv: ^6.0.0
  slide_to_act: ^2.0.2
  supabase_flutter: ^2.10.3
  rxdart: ^0.28.0
  top_snackbar_flutter: ^3.3.0
  geocoding: ^4.0.0
  lottie: ^3.3.1
  image_picker: ^1.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  very_good_analysis: ^9.0.0
  flutter_lints: ^5.0.0
  dart_code_metrics_presets: ^2.26.1

  auto_route_generator: ^10.2.4
  build_runner: ^2.7.1


flutter:
  generate: true

  uses-material-design: true


  assets:
    - .env
    - assets/images/
    - assets/vectors/
    - assets/lottie/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-SemiBold.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-ExtraBold.ttf
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
    - family: Carme
      fonts:
        - asset: assets/fonts/Carme/Carme-Regular.ttf
